### ISSUE TITLE
Docker build fails

### ISSUE THREAD

**Issue by beanie999** [newrelic-experimental/newrelic-logs-for-salesforce-commerce-cloud#3]
[NOTE]: # ( ^^ Provide a general summary of the issue in the title above. ^^ )

## Description

[NOTE]: # ( Describe the problem you're encountering. )
[TIP]:  # ( Do NOT give us access or passwords to your New Relic account or API keys! )

Docker build command fails, output from the build:

Sending build context to Docker daemon  138.8kB
Step 1/14 : FROM node:current-alpine
 ---> 182dfd1d5db3
Step 2/14 : USER root
 ---> Using cache
 ---> 9cda5602e34b
Step 3/14 : RUN apk add --no-cache --update git   && git clone https://github.com/newrelic-forks/cctail.git cctail
 ---> Using cache
 ---> 58e3244f80dc
Step 4/14 : COPY package.json /cctail
 ---> Using cache
 ---> 3ae6451c7e65
Step 5/14 : WORKDIR /cctail
 ---> Using cache
 ---> 15f84efbb519
Step 6/14 : RUN npm install
 ---> Running in 15f4d552e329

\> cctail@1.6.0 prepare
\> npm run build

\> cctail@1.6.0 build
\> tsc

src/cctail.ts(47,12): error TS2339: Property 'd' does not exist on type '{ [x: string]: unknown; _: (string | number)[]; $0: string; } | Promise<{ [x: string]: unknown; _: (string | number)[]; $0: string; }>'.
  Property 'd' does not exist on type 'Promise<{ [x: string]: unknown; _: (string | number)[]; $0: string; }>'.
src/cctail.ts(53,36): error TS2339: Property '_' does not exist on type '{ [x: string]: unknown; _: (string | number)[]; $0: string; } | Promise<{ [x: string]: unknown; _: (string | number)[]; $0: string; }>'.
  Property '_' does not exist on type 'Promise<{ [x: string]: unknown; _: (string | number)[]; $0: string; }>'.
src/cctail.ts(55,40): error TS2339: Property '_' does not exist on type '{ [x: string]: unknown; _: (string | number)[]; $0: string; } | Promise<{ [x: string]: unknown; _: (string | number)[]; $0: string; }>'.
  Property '_' does not exist on type 'Promise<{ [x: string]: unknown; _: (string | number)[]; $0: string; }>'.
npm notice 
npm notice New minor version of npm available! 9.6.4 -> 9.8.0
npm notice Changelog: <https://github.com/npm/cli/releases/tag/v9.8.0>
npm notice Run \`npm install -g npm@9.8.0\` to update!
npm notice 
npm ERR! code 2
npm ERR! path /cctail
npm ERR! command failed
npm ERR! command sh -c npm run build

npm ERR! A complete log of this run can be found in: /root/.npm/_logs/2023-07-19T14_09_01_766Z-debug-0.log
The command '/bin/sh -c npm install' returned a non-zero code: 2

## Steps to Reproduce

[NOTE]: # ( Please be as specific as possible. )
Run the build script provided in the repo.

## Expected Behavior

[NOTE]: # ( Tell us what you expected to happen. )
Docker build should complete successfully.

## Relevant Logs / Console output

[NOTE]: # ( Please provide specifics of the local error logs, Browser Dev Tools console, etc. if appropriate and possible. )
See above.

## Your Environment

Linux mike-ubuntu 5.15.0-71-generic #78-Ubuntu SMP Tue Apr 18 09:00:29 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux
Docker version 20.10.24, build 297e128

## Additional context
None

**Comment by beanie999** [comment]
Changing the RUN npm install line in the Dockerfile to the below seems to fix this:
`RUN npm install -g npm@9.8.0`

**Comment by MaartenFaddegon** [comment]
I believe the error is in the New Relic fork of `cctail`. When I update the `Dockerfile` to use the original version the docker build succeeds.

![Screenshot 2023-07-24 at 15 06 51](https://github.com/newrelic-experimental/newrelic-logs-for-salesforce-commerce-cloud/assets/2544690/46cb0147-59d3-4740-b862-f27a747d95ee)

New Relic team, @sschwartzman, are there any essential changes in your cctail fork?

**Comment by sschwartzman** [comment]
Sorry but I left NR a year ago, so I am no longer involved in maintaining this package.

**Comment by ricegi** [comment]
Hey @MaartenFaddegon - we've identified this as a problem with typescript version being specified by cctail. Because the dependency is clone our cctail. We think this PR will fix it - I'll see what's keeping the PR being accepted https://github.com/newrelic-forks/cctail/pulls

**Comment by ricegi** [comment]
@MaartenFaddegon - fix should have been merged for the typescript issue - if you can validate we'll close off this issue

**Comment by ricegi** [comment]
validated fixed
