### ISSUE TITLE
No entrypoint for Docker container init

### ISSUE THREAD

**Issue by ricegi** [newrelic-experimental/newrelic-logs-for-salesforce-commerce-cloud#4]
## Description

There appears to be no ENTRYPOINT or CMD command to initiate any process when the container is deployed. We noticed an entrypoint script ([link](https://github.com/newrelic-experimental/newrelic-logs-for-salesforce-commerce-cloud/blob/main/entrypoint.sh)) but couldn't find where it is being called or executed. We tried executing the script manually inside the deployed container without success.

**Comment by jbeveland27** [comment]
Did some digging, found out the entrypoint script defined in our repo is automatically invoked from the fluentd base image.

The [base image](https://github.com/newrelic-experimental/newrelic-logs-for-salesforce-commerce-cloud/blob/main/Dockerfile#L10) is [fluent/fluentd:edge](https://github.com/newrelic-experimental/newrelic-logs-for-salesforce-commerce-cloud/blob/main/Dockerfile#L10C25-L10C25), which has an [ENTRYPOINT defined](https://github.com/fluent/fluentd-docker-image/blob/master/v1.16/alpine/Dockerfile#L48):

`ENTRYPOINT ["tini",  "--", "/bin/entrypoint.sh"]`

Our Dockerfile [copies entrypoint.sh](https://github.com/newrelic-experimental/newrelic-logs-for-salesforce-commerce-cloud/blob/main/Dockerfile#L21C11-L21C11) over to `/bin/entrypoint.sh` so it's available when the base image runs the `ENTRYPOINT`. 

Thus, the entrypoint.sh is executed automatically when the container is run.
